version: 2.1


jobs:
  ui-web-testing:
    docker:
      - image: cimg/openjdk:17.0-browsers


    working_directory: ~/ui_api_testing

    environment:
      MAVEN_OPTS: -Xmx4200m -Xms1024m

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Docker Compose Up
          command: |
            cd ui-compend
            sudo chown $USER:$USER -R .
            docker-compose -f docker-compose.yml up -d
            sleep 100

      - restore_cache:
          keys:
            - $CIRCLE_PROJECT_REPONAME-{{ checksum "pom.xml" }}
            - $CIRCLE_PROJECT_REPONAME-

      - run: mvn dependency:go-offline compile compiler:testCompile
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run:
          name: Run UI Tests
          command: mvn clean test -pl ui-compend -e
          when: always

      - run:
          name: Make history dir for allure reports
          command: mkdir ui-compend/target/allure-results/history
          when: always

      - run:
          name: Get previous artifact links
          command: |
            echo $CIRCLE_API_TOKEN
            CIRCLE_PREVIOUS_BUILD_NUM= expr $CIRCLE_BUILD_NUM - 1
            curl https://circleci.com/api/v2/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$CIRCLE_API_TOKEN | grep -o 'https:\/\/[^"]*Allure\/history\/.*\.json' > artifacts.txt || true
            pwd
            ls -l
          when: always

      - run: cat artifacts.txt || true

      - run:
          name: Download artifacts history
          command: <artifacts.txt xargs -P4 -I % wget $?circle-token=$CIRCLE_API_TOKEN
          when: always

      - run:
          name: Rename and copy history artifacts to allure-result
          command: |
            pwd
            ls -l ui-compend         
            mv history.json?circle-token=$CIRCLE_API_TOKEN history.json && mv history-trend.json?circle-token=$CIRCLE_API_TOKEN history-trend.json || true
            cp history.json ui-compend/target/allure-results/history/ && cp history-trend.json ui-compend/target/allure-results/history/ || true
            mv categories-trend.json?circle-token=$CIRCLE_API_TOKEN categories-trend.json && mv duration-trend.json?circle-token=$CIRCLE_API_TOKEN duration-trend.json || true
            cp categories-trend.json ui-compend/target/allure-results/history/ && cp duration-trend.json ui-compend/target/allure-results/history/ || true
            mv retry-trend.json?circle-token=$CIRCLE_API_TOKEN retry-trend.json || true
            cp retry-trend.json ui-compend/target/allure-results/history/ || true
            ls -l ui-compend/target/allure-results || true
          when: always

      - run:
          name: Save test results
          command: |
            mkdir -p ~/ui-compend/test-results/junit/
            find . -type f -regex ".*/ui-compend/target/surefire-reports/junitreports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/ui-compend/test-results

      - store_artifacts:
          path: ~/ui-compend/test-results/junit

      - run:
          name: Generate Allure report
          command: mvn allure:report -pl ui-compend
          when: always

      - store_artifacts:
          path: ui-compend/target/site/allure-maven-plugin
          destination: Allure

      - run:
          name: Check artifacts
          command: | 
            ls -l ui-compend/target/site/allure-maven-plugin || true
            pwd
            ls -l ui-compend/target/site/allure-maven-plugin/history || true



workflows:
  regression:
    jobs:
      - ui-web-testing

