version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  ui-web-testing:
    docker:
      - image: cimg/openjdk:17.0-browsers


    working_directory: ~/ui-compend

    environment:
      MAVEN_OPTS: -Xmx4200m -Xms1024m

    steps:
      - checkout

      - run:
          name: Ifconfig
          command: ifconfig
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Docker Compose Up
          command: |
            cd ui-compend
            sudo chown $USER:$USER -R .
            docker-compose -f docker-compose.yml up -d

      - run:
          name: Check Running Containers
          command: docker ps
      - run:
          name: Check 4444 port
          command: sudo ss -tunlp | grep 4444
      - run:
          name: Get Selenium Grid Status
          command: curl 'http://localhost:4444/status'


      - restore_cache:
          keys:
            - $CIRCLE_PROJECT_REPONAME-{{ checksum "pom.xml" }}
            - $CIRCLE_PROJECT_REPONAME-

      - run: mvn dependency:go-offline compile compiler:testCompile
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - run:
          name: Run UI Tests
          command: mvn clean test -pl ui-compend -e
          when: always

workflows:
  regression:
    jobs:
      - ui-web-testing

