version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  ui-web-testing:
    docker:
      - image: cimg/openjdk:17.0-browsers

    working_directory: ~/ui-compend

    environment:
      MAVEN_OPTS: -Xmx4200m -Xms1024m

    steps:
      - checkout
#      - browser-tools/install-chrome
#      - browser-tools/install-firefox
#      - browser-tools/install-edge

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Verify Docker  And Docker Compose Version
          command: |
            docker-compose --version
            docker --version

      - run:
          name: Add User To The Docker Group
          command: sudo usermod -aG docker ${USER}

      - run:
          name: Docker Compose Up
          command: |
            cd ui-compend
            sudo chown $USER:$USER -R .
            docker-compose -f docker-compose.yml up -d

workflows:
  regression:
    jobs:
      - ui-web-testing

